### ISSUE TITLE
dynamic component imports exhibit inconsistent behavior

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent#14]
Using async components inside loaders is exhibiting weird, inconsistent behavior.

This method only works if the project is in the same directory as Nuxt root. 

1.

```
components {
   SomeComponent: () => import('~components/someComponent') 
}
```

This method works even if the directory is not the same as Nuxt root, but it's not async. 

2. 

```
components {
   SomeComponent: require(["~components/${name + ext}"])
}
```

So I used guards to check if the directories matched to choose which method to use, but of course, even though the first method worked in the same directory as the package, when I tried to test it externally, it didn't work (`import` was an unexpected token).

Only this third approach worked in an external directory.

3. 
```
components {
   SomeComponent: `(resolve) => require(["~components/${name + ext}"], resolve)`
}
```

But even if it worked with `nuxt dev`, it failed when I tried to run it with `nuxt generate`...

```
ERROR in nuxt.bundle.3107bd9208454be22be2.js from UglifyJs
Unexpected token: punc ([) [nuxt.bundle.3107bd9208454be22be2.js:1191,4]
```

Hmm..

Only the standard approach so far works in all situations: 

4.
```
import SomeComponent from '~component/someComponent'

export default {
  components: {
    SomeComponet
  }
}

```

Not sure if this is an issue with Nuxt, with Vue loader, or with the usage of dynamic imports inside loaders. 

Going to stick the fourth approach in the meantime.

**Comment by alidcastano** [comment]
Waiting till the release of Nuxt 1.0 which uses Vue 2.4 to give this another shot.

**Comment by bovas85** [comment]
Vue 2.5 is released, have you got any update on this @alidcastano ?

**Comment by alidcastano** [comment]
I haven't had a chance and tbh totally forgot about this. Right now markdown components work, but they are imported normally. Feel free to open up a new issue if you'd like this feature so that we can track it better.
