### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by levibostian** [nuxt-community/nuxtent#24]
nuxtent version: "nuxtent": "^0.2.27",

I have a nuxtent project that I built by checking out the nuxtent-starter template project. I got nuxtent up and running with 1 content type:

```
module.exports = {
  content: {
    routeName: 'freelance-slug',
    permalink: 'freelance/:slug', 
    isPost: false    
  }
}
```

So, when I go to localhost:3000/freelance/foo I am showing data from /content/freelance/foo.md. 

I am now trying to use multiple content types. The only thing that I change is my `nuxtent.config.js` file to the following:

```
module.exports = {
  content: {
    ['freelance', {
      routeName: 'freelance-slug',
      permalink: 'freelance/:slug', 
      isPost: false
    }],
    ["opensource", {
      routeName: "opensource-slug",
      permalink: "opensource/:slug",
      isPost: false
    }]
   ]
  }
}
```

Pretty simple here. Same configuration as before but adding another type, `opensource`. 

When I run `npm run dev` with this configuration, I am getting the output:

```
> ./node_modules/nuxt/bin/nuxt

(node:59448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ,
(node:59448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): SyntaxError: Unexpected token ,
```

The build is unsuccessful with this error and I am not able to move beyond it.

**Comment by alidcastano** [comment]
What version of `nuxtent` are you using? I just ran the `multiple-content-type` example which uses the same setup and there weren't any problems. Can you try running that? 

If that doesn't work, please let me know the version and environment you are running on, so that I can better narrow down the issue.

**Comment by alidcastano** [comment]
Also, it looks like you have an unnecessary `]` in the bottom there.

**Comment by roikiermedia** [comment]
On the docs the code example is multiple arrays nested inside an object and not multiple arrays in an array.

**Comment by alidcastano** [comment]
Haha wow sorry for that 😅  I've been trying to move fast w/ Nuxtent so pointing out mistakes like that, which are easy to miss, is helpful. 

I've made the change in docs, which will reflect in next release. Assuming that fixes the error, I'll go ahead and close this issue now. Feel free to open it back up if I'm wrong.

Thanks @roikiermedia and @levibostian

**Comment by levibostian** [comment]
Yup. [@roikiermedia's comment](https://github.com/nuxt-community/nuxtent/issues/24#issuecomment-317457649) was the issue. `content` was an object instead of an array. I have been following the docs resources closely to get this up and running. 

I have finally gotten it to work. Time for me to start writing some content! 

I found a couple issues with the docs myself while working through setting up site. I will comment on them in repo in separate issues.

**Comment by alidcastano** [comment]
That's a huge help, thanks @levibostian
