### ISSUE TITLE
Example code in docs for `asyncData()` is not working. 

### ISSUE THREAD

**Issue by levibostian** [nuxt-community/nuxtent#26]
While viewing the docs on [rendering content](https://nuxtent.now.sh/usage#rendering-content), the docs show this code snippet that you put into your nuxt page:

```
async asyncData ({ app, route, payload }) {
  return {
    post: app.$content('/posts').get(route.path) || payload
  }
}
```

I entered this code into my nuxt page and it did not render the content from my .md file into the page. 

I replaced the code snippet with the code snippet from the template project:

```
asyncData: async ({ app, route, payload }) => ({
    post: await app.$content('/posts').get(route.path) || payload
  })
```

With success. 

I am not sure why this makes a difference? The syntax seems as though it should work either way, however, through my testing that does not seem to be the case.

**Comment by alidcastano** [comment]
Yea, in the first method, you need to await the `$content` data, as well.

It should be like this:

```
async asyncData ({ app, route, payload }) {
  return {
    post: await app.$content('/posts').get(route.path) || payload
  }
}

```

I'll close this and update docs, thanks for that. Feel free to open issues or PRs if you notice anything else is wrong or can be better clarified.
